#!/bin/bash
exec > /root/res/rep.log 2>&1
K=/root/jobs/knee.sh; T=/root/mflags
ALL="MYNAH_CANCEL_CHECK_EVERY=4 MYNAH_STREAM_OUT_WRITEV=1 MYNAH_DUP_CHECK_EPOCH=1 MYNAH_CUDA_DECODER_TABLE_PATCH=1 MYNAH_CUDA_ONESYNC_SUBSET=1 MYNAH_CUDA_DEFERRED_RELEASE=1 MYNAH_STREAM_DELIVER_THREADS=4 MYNAH_CUDA_PCM_DIRECT=1 MYNAH_CUDA_HIDDEN_LAZY=1 MYNAH_CUDA_KV_TABLE_CACHE=1 MYNAH_CUDA_DECODER_VALIDATE_ONCE=1"
echo "== rep start $(date -u +%T)"
for r in 1 2; do
  TREE=$T TAG=r$r-base LEVELS="640 768 896" PROCS=4 DUR=120 timeout 1500 $K
  TREE=$T TAG=r$r-all LEVELS="640 768 896" PROCS=4 DUR=120 ENVS="$ALL" timeout 1500 $K
done
echo "== rep done $(date -u +%T)"
