#!/bin/bash
exec > /root/res/speed.log 2>&1
K=/root/jobs/knee.sh; T=/root/mflags
ALL="MYNAH_CANCEL_CHECK_EVERY=4 MYNAH_STREAM_OUT_WRITEV=1 MYNAH_DUP_CHECK_EPOCH=1 MYNAH_CUDA_DECODER_TABLE_PATCH=1 MYNAH_CUDA_ONESYNC_SUBSET=1 MYNAH_CUDA_DEFERRED_RELEASE=1 MYNAH_STREAM_DELIVER_THREADS=4 MYNAH_CUDA_PCM_DIRECT=1 MYNAH_CUDA_HIDDEN_LAZY=1 MYNAH_CUDA_KV_TABLE_CACHE=1 MYNAH_CUDA_DECODER_VALIDATE_ONCE=1"
echo "== speed start $(date -u +%T)"
TREE=$T TAG=s-base LEVELS="640 768 896" PROCS=4 DUR=60 timeout 1500 $K
TREE=$T TAG=s-all LEVELS="640 768 896" PROCS=4 DUR=60 ENVS="$ALL" timeout 1500 $K
for arm in "L6|MYNAH_CUDA_DEFERRED_RELEASE=1" "L7L8|MYNAH_CANCEL_CHECK_EVERY=4 MYNAH_STREAM_OUT_WRITEV=1" "L10|MYNAH_DUP_CHECK_EPOCH=1" "L11|MYNAH_CUDA_DECODER_TABLE_PATCH=1" "L12|MYNAH_CUDA_ONESYNC_SUBSET=1" "L19|MYNAH_STREAM_DELIVER_THREADS=4" "L20|MYNAH_CUDA_PCM_DIRECT=1" "L21|MYNAH_CUDA_HIDDEN_LAZY=1" "L22|MYNAH_CUDA_KV_TABLE_CACHE=1" "L24|MYNAH_CUDA_DECODER_VALIDATE_ONCE=1"; do
  L="${arm%%|*}"; E="${arm#*|}"
  TREE=$T TAG=s-$L LEVELS="640 768" PROCS=4 DUR=60 ENVS="$E" timeout 1200 $K
done
echo "== speed done $(date -u +%T)"
